; PlatformIO Project Configuration File
;
; https://docs.platformio.org/page/projectconf.html

[env:m5stack-coreink]
platform = espressif32
board = m5stack-coreink
framework = arduino
monitor_speed = 115200
lib_deps =
    m5stack/M5Core-Ink @ ^1.0.0
    m5stack/M5GFX @ ^0.2.0
    bblanchon/ArduinoJson @ ^7.0.0
build_flags =
    -DCORE_DEBUG_LEVEL=0
